version: 2
updates:
- package-ecosystem: "cargo"
  open-pull-requests-limit: 0
  directory: "/"
  schedule:
    interval: "daily"
- package-ecosystem: "github-actions"
  open-pull-requests-limit: 0
  directory: "/"
  schedule:
    interval: "daily"
- package-ecosystem: npm
  open-pull-requests-limit: 0
  directory: "/washboard"
  schedule:
    interval: "daily"
